version: '3'

services:
  db:
    #image: mysql:8.0.25
    image: postgres:14
    #command: --default-authentication-plugin=mysql_native_password
    volumes:
      #- ./api/db/mysql_data:/var/lib/mysql
      #- db-volume:/var/lib/mysql
      #- ./api/db/postgres-data:/var/lib/postgresql/data
      #- ./api/db/postgres-data:/var/lib/postgresql
      - db-volume:/var/lib/postgresql/data
    environment:
    #    MYSQL_ROOT_PASSWORD: password
        POSTGRES_PASSWORD: password
  api:
    build: 
      context: ./api/
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f /myapp/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    #command: /bin/sh -c "rm -f /myapp/tmp/pids/server.pid && bundle exec rdebug-ide --host '0.0.0.0' --port 1234 --dispatcher-port 26162 -- bin/rails server -b '0.0.0.0'"
    image: rails:dev
    volumes:
      - ./api:/myapp
      - ./api/vendor/bundle:/myapp/vendor/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
      CORS_ALLOWED_ORIGINS: http://localhost:8000
    ports:
      - 3000:3000
    #  - 1234:1234 #debug
    #  - 26162:26162 #debug
    depends_on:
      - db
    #debug(pry)
    tty: true
    stdin_open: true
  front:
    build: 
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - ./front:/usr/src/app
    command: sh -c "cd react-sample && yarn start"
    ports:
      - "8000:3000"
volumes:
  db-volume: